[TGUI] APC, Vending and SimpleDockingConsole
ss220club/WyccerraBay220 pull request #64
Opened 2024-02-12 11:57 UTC by AyIong

## Что этот PR делает
Тырфейсы для АПЦ, вендоров и докинг консоли, как видно из названия

## Почему это хорошо для игры
Удобно, красиво, криво.

## Изображения изменений
<details>
<summary>APC</summary>

![image](https://github.com/ss220club/WyccerraBay220/assets/69762909/defc9886-d6a3-4ca9-b481-7db76588cad8)

</details>

<details>
<summary>Vending</summary>

https://github.com/ss220club/WyccerraBay220/assets/69762909/54d25a8a-dd68-4036-94aa-2a40d5d753ef

</details>

## Тестирование
Ага, уверен что-то пропустил так как билд не знаю и код для меня выглядит как спагетти

## Changelog

:cl:
add: Вендоры, АПЦ и SimpleDockingConsole теперь на TGUI
/:cl:

2024-02-12 14:14 UTC, Gaxeer requested changes

2024-02-12 14:14 UTC, Gaxeer commented on code/game/machinery/embedded_controller/simple_docking_controller.dm
>  		ui.open()
`autoupdate` имеет `TRUE` по умолчанию

2024-02-12 14:14 UTC, Gaxeer commented on code/modules/power/apc.dm
> +			src.overload_lighting()
```suggestion
			overload_lighting()
```

2024-02-12 14:14 UTC, Gaxeer commented on code/modules/tgui/tgui.dm
> +		addtimer(new Callback(src, PROC_REF(send_full_update)), TGUI_REFRESH_FULL_UPDATE_COOLDOWN, TIMER_UNIQUE)
```suggestion
		addtimer(CALLBACK(src, PROC_REF(send_full_update)), TGUI_REFRESH_FULL_UPDATE_COOLDOWN, TIMER_UNIQUE)
```

2024-02-12 14:14 UTC, Gaxeer commented on code/modules/tgui/tgui.dm
> +		addtimer(new Callback(src, PROC_REF(send_full_update)), TGUI_REFRESH_FULL_UPDATE_COOLDOWN, TIMER_UNIQUE)
Я вернул макрос

2024-02-12 14:16 UTC, Gaxeer commented
Ребейзнись на `master`

2024-02-12 17:35 UTC, AyIong commented on code/game/machinery/embedded_controller/simple_docking_controller.dm
>  		ui.open()
Так интерфейс копеечный, пускай автоматически обновляется, иначе только при действиях будет

2024-02-14 14:14 UTC, Gaxeer approved these changes
О да

2024-02-14 14:14 UTC, merged