Components + Pixel Shift
ss220club/WyccerraBay220 pull request #85
Opened 2024-02-14 15:53 UTC by larentoun

## Что этот PR делает

Добавляет компоненты с ТГ
Добавляет пиксель шифт, который использует компоненты и сигналы

## Почему это хорошо для игры

ТГфикация

## Тестирование

- Походил сквозь шифтнутые куклы
- Пострелял в противоположный угол турфа куклы - попал
- Лег - шифт убрался
- Мув - шифт убрался

## Changelog

:cl:
add: Пиксель шифт
/:cl:

2024-02-14 15:55 UTC, larentoun commented
При тест мерже может сломаться разве что BuckleRestLyingComb... Короче обновление иконки куклы

2024-02-14 15:56 UTC, Gaxeer commented on code/controllers/subsystems/dcs.dm
> +	wait = 1 SECONDS
не вижу fire

2024-02-14 15:58 UTC, larentoun commented on code/controllers/subsystems/dcs.dm
> +	wait = 1 SECONDS
Тык с /processing наследуется, не так?

2024-02-14 16:01 UTC, Gaxeer commented on code/controllers/subsystems/dcs.dm
> +	wait = 1 SECONDS
не заметил

2024-02-16 12:06 UTC, larentoun commented
А че тест упал Madge

2024-02-16 12:44 UTC, larentoun commented
А щас тесты встали, чзх

2024-02-16 12:56 UTC, AyIong commented
> А щас тесты встали, чзх

У карты сыра рандомное падение

2024-02-16 13:01 UTC, Furrior commented on code/__defines/dcs/flags.dm
> +#define ELEMENT_BESPOKE (1 << 1)
Волшебник ебанный, как у тебя это тесты прошло? Там же требует FLAG использовать вместо битшифтов

2024-02-16 13:02 UTC, larentoun commented on code/__defines/dcs/flags.dm
> +#define ELEMENT_BESPOKE (1 << 1)
Я удалил тест Jokerge

2024-02-16 13:05 UTC, Furrior commented on code/__defines/dcs/flags.dm
> +#define ELEMENT_BESPOKE (1 << 1)
Так это еще более менее тема была же. Даже удобно, вроде

2024-02-16 13:17 UTC, larentoun commented on code/__defines/dcs/flags.dm
> +#define ELEMENT_BESPOKE (1 << 1)
Вернул

2024-02-16 14:11 UTC, larentoun commented
обновил кейбинд, убрал легаси с копипасты Clueless

2024-02-16 14:58 UTC, Furrior requested changes

2024-02-16 14:58 UTC, Furrior commented on code/modules/mob/living/life.dm
> +		regenerate_icons()
```suggestion
	if(update_icon)	//forces a full overlay update
		update_icon = FALSE
		regenerate_icons()
```

2024-02-16 14:58 UTC, Furrior commented on code/game/atoms_movable.dm
>  			GLOB.moved_event.raise_event(src, old_loc, null)
```suggestion
	
	. = ..()
	if (!.)
		return
	var/old_loc = loc
	SEND_SIGNAL(src, COMSIG_MOVABLE_MOVED, old_loc)
	if(!loc)
		GLOB.moved_event.raise_event(src, old_loc, null)
		
```

2024-02-16 16:41 UTC, larentoun commented on code/game/atoms_movable.dm
>  			GLOB.moved_event.raise_event(src, old_loc, null)
лок меняется при ..()

2024-02-16 16:41 UTC, larentoun commented on code/game/atoms_movable.dm
>  			GLOB.moved_event.raise_event(src, old_loc, null)
Или я запутался в этих мувах

2024-02-16 19:16 UTC, Furrior approved these changes
Ну выглядит правдоподобно

2024-02-20 22:49 UTC, Gaxeer approved these changes

2024-02-20 22:50 UTC, merged